### ISSUE TITLE
Not possible to save changes in indicators names

### ISSUE THREAD

**Issue by JudaGarcia99** [amilcar-capsus/UPT-GUI#3]
Looking to define friendly names to the indicators so the user understands what is it about, after clicking in the save option does nothing happen.

Taking a look in the developer's tool this is the error message obtained

![image](https://user-images.githubusercontent.com/63655568/79602129-8a87a900-80af-11ea-8d78-0c13407eb670.png)

**Comment by amilcar-uptech** [comment]
Make sure that you add at least one character to the description and try again. The error message is stating that no description is being sent, as it is a required field.

**Comment by JudaGarcia99** [comment]
By adding a description it worked
